[package]
name = "langulo"
version = "0.1.0"
edition = "2024"

[dependencies]
# lexer
logos = "0.16.0"
# parser
rowan = "0.16.1"
# TUI
clap = { version = "4", features = ["derive"] }
rustyline = "17.0.2"
colored = "3.0.0"
# error handling
thiserror = "2.0.17"
miette = { version = "7.6.0", features = ["fancy"] }
# python interop
pyo3 = { version = "<=0.20.2", features = ["auto-initialize"] }