[package]
name = "languria2"
version = "0.1.0"
edition = "2024"

[dependencies]
# lexer
logos = "0.16.0"
# parser
rowan = "0.15"
# TUI
clap = { version = "4", features = ["derive"] }
rustyline = "14"
colored = "2"
# error handling
thiserror = "1"
miette = { version = "5", features = ["fancy"] }
# python interop
pyo3 = { version = "<=0.20.2", features = ["auto-initialize"] }